(() => {
  const $ = id => document.getElementById(id);
  const STORE = 'ktv-wheel-v1';
  let state = readState();
  let draft = [];
  let busy = false;
  const canvas = $('wheel'), ctx = canvas.getContext('2d');
  const palette = ['#e6b65f','#a665d8','#5c86d8','#e27682','#59b7a9','#b48aeb','#d88956','#668bc2'];
  function clean(s){ return String(s || '').replace(/^\s*(?:\d+[.、)）]|[-*•])\s*/, '').trim(); }
  function unique(lines){ const seen = new Set(); return lines.map(clean).filter(s => {const key=s.toLocaleLowerCase();if(!s||seen.has(key))return false;seen.add(key);return true;}); }
  function lines(text){return unique(text.split(/\r?\n/));}
  function readState(){try {const v=JSON.parse(localStorage.getItem(STORE)); if(v&&Array.isArray(v.songs)&&Array.isArray(v.history)){const songs=unique(v.songs);const history=v.history.filter(x=>songs.includes(x));return {songs,history};}}catch{} return {songs:[],history:[]};}
  function save(){localStorage.setItem(STORE,JSON.stringify(state));}
  const remaining = () => state.songs.filter(s => !state.history.includes(s));
  function show(view){['importView','reviewView','gameView'].forEach(id => $(id).hidden=id!==view);$('editBtn').hidden=view!=='gameView';}
  function escapeText(s){const e=document.createElement('span');e.textContent=s;return e.textContent;}
  function render(){if(!state.songs.length){show('importView');return;}show('gameView');const pool=remaining();$('remaining').textContent=pool.length;$('total').textContent=state.songs.length;$('drawCount').textContent=`已抽 ${state.history.length} 首`;$('historyCount').textContent=state.history.length;$('statusTitle').textContent=pool.length?'':'全部抽完啦';$('spinBtn').disabled=!pool.length||busy;$('spinBtn').textContent=pool.length?'抽一首':'结束';$('resultName').textContent=state.history.at(-1)||'还没有抽取';$('historyList').replaceChildren(...state.history.map((song,i)=>{const li=document.createElement('li');li.textContent=`${i+1}. ${song}`;return li;}));drawWheel(pool);}
  function drawWheel(pool){const n=pool.length; const w=canvas.width,c=w/2,r=c-12;ctx.clearRect(0,0,w,w);if(!n){ctx.fillStyle='#403456';ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fill();ctx.textAlign='center';ctx.fillStyle='#fff1c9';ctx.font='bold 42px sans-serif';ctx.fillText('全部抽完',c,c-115);return;}
    const step=Math.PI*2/n; for(let i=0;i<n;i++){let a=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,a,a+step);ctx.closePath();ctx.fillStyle=palette[i%palette.length];ctx.fill();ctx.strokeStyle='#1e1935';ctx.lineWidth=n>100?1:3;ctx.stroke();if(n<=36){ctx.save();ctx.translate(c,c);ctx.rotate(a+step/2);ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillStyle='#1b1830';ctx.font=`bold ${n>20?20:n>12?25:32}px sans-serif`;let limit=n>20?6:n>12?9:13;let name=pool[i].length>limit?pool[i].slice(0,limit-1)+'…':pool[i];ctx.fillText(name,r-24,0,r*.68);ctx.restore();}}
    ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.strokeStyle='#f5dfa4';ctx.lineWidth=9;ctx.stroke();if(n>36){ctx.fillStyle='#fff5db';ctx.textAlign='center';ctx.font='bold 37px sans-serif';ctx.fillText(`${n} 首待抽`,c,c-125);}}
  function review(items){draft=unique(items);$('reviewText').value=draft.join('\n');$('reviewCount').textContent=`识别出 ${draft.length} 首，请核对后确认`;show('reviewView');}
  $('plainBtn').onclick=()=>{if($('images').files.length){$('importError').textContent='图片需要使用智能识别，并填写 API Key。';return;}const arr=lines($('rawText').value);if(!arr.length){$('importError').textContent='先粘贴至少一首歌。';return;}$('importError').textContent='';review(arr);};
  $('images').onchange=()=>{$('fileCount').textContent=$('images').files.length?`已选 ${$('images').files.length} 张图片`:'尚未选择图片';};
  $('backBtn').onclick=()=>show('importView');
  $('reviewText').oninput=()=>{$('reviewCount').textContent=`当前 ${lines($('reviewText').value).length} 首`;};
  $('confirmBtn').onclick=()=>{const arr=lines($('reviewText').value);if(!arr.length){$('reviewCount').textContent='至少保留一首歌';return;}state={songs:arr,history:[]};save();render();};
  $('editBtn').onclick=()=>{if(!confirm('编辑歌单会清空本轮抽取记录，确定继续吗？'))return;$('rawText').value=state.songs.join('\n');$('images').value='';$('fileCount').textContent='尚未选择图片';show('importView');};
  $('resetBtn').onclick=()=>{if(!state.history.length)return;if(confirm('把已抽歌曲全部放回转盘，重新开始本轮？')){state.history=[];save();render();}};
  $('spinBtn').onclick=()=>{const pool=remaining();if(busy||!pool.length)return;busy=true;$('spinBtn').disabled=true;$('spinBtn').textContent='转动中';const i=Math.floor(Math.random()*pool.length), n=pool.length;const offset=360*(i+.5)/n;const turns=360*(5+Math.floor(Math.random()*3));let target=turns-offset;while(target<1800)target+=360;canvas.style.transition='none';canvas.style.transform='rotate(0deg)';void canvas.offsetWidth;canvas.style.transition='transform 4.2s cubic-bezier(.13,.72,.14,1)';canvas.style.transform=`rotate(${target}deg)`;setTimeout(()=>{state.history.push(pool[i]);save();$('resultName').textContent=pool[i];$('result').animate([{boxShadow:'0 0 0 0 #e5b35488'},{boxShadow:'0 0 0 13px #e5b35400'}],{duration:800});setTimeout(()=>{canvas.style.transition='none';canvas.style.transform='none';busy=false;render();},1150);},4200);};
  async function fileData(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('仅支持 JPG、PNG 或 WebP 图片');if(file.size>12*1024*1024)throw Error('单张图片请小于 12 MB');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('图片读取失败'));reader.readAsDataURL(file);});}
  $('parseBtn').onclick=async()=>{const key=$('apiKey').value.trim(), raw=$('rawText').value.trim(), files=[...$('images').files];if(!raw&&!files.length){$('importError').textContent='先输入文字或选择图片。';return;}if(!key){$('importError').textContent='智能识别需要填写 DeepSeek API Key；规则整齐的文字可用「按行直接导入」。';return;}const button=$('parseBtn');button.disabled=true;button.textContent='正在识别…';$('importError').textContent='';try{if(files.length>5)throw Error('一次最多选择 5 张图片');const content=[{type:'text',text:'从以下文字与图片提取歌曲。只返回 JSON 对象，格式 {"songs":[{"title":"歌名","artist":"歌手"}]}。不要编造没出现的歌；不确定的歌手留空；去掉重复歌曲。文字：\n'+raw}];for(const file of files)content.push({type:'image_url',image_url:{url:await fileData(file),detail:'high'}});const response=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'deepseek-flash',messages:[{role:'user',content}],response_format:{type:'json_object'},stream:false})});const data=await response.json();if(!response.ok)throw Error(data.error?.message||`请求失败 (${response.status})`);let parsed=JSON.parse(data.choices?.[0]?.message?.content||'{}');let songs=Array.isArray(parsed)?parsed:parsed.songs;if(!Array.isArray(songs))throw Error('模型没有返回可识别的歌单，请重试');let items=unique(songs.map(x=>typeof x==='string'?x:[x.title,x.artist].filter(Boolean).join(' - ')));if(!items.length)throw Error('没有识别到歌曲，可以试试更清晰的图片');review(items);}catch(e){$('importError').textContent=e instanceof TypeError?'连接 DeepSeek 失败。若浏览器阻止跨域请求，需改用代理服务；文字仍可按行直接导入。':e.message;}finally{button.disabled=false;button.textContent='智能识别歌单';}};
  render();
})();
